### reading data
GET http://localhost:4004/BooksSRV/Books?$expand=author,address HTTP/1.1

### reading authors data

GET http://localhost:4004/BooksSRV/Address HTTP/1.1

### creating author

POST http://localhost:4004/BooksSRV/Authors HTTP/1.1
Content-Type: application/json


{
    "ID": "9a9349f3-efe4-11ee-96b0-0800200c9a66",
      "name": "ujwala"
}

### creating books
POST http://localhost:4004/BooksSRV/Books HTTP/1.1
Content-Type: application/json


{
 "ID": "9a9349f1-efe4-11ee-96b0-0800200c9a66",
      "title": "SAP EWM",
      "descr": "EWM programming architecture",
      "amount": 900,
      "email": "ujwala@gmail.com",
      "phone": "9901706243",
      "author_ID": "9a9349f3-efe4-11ee-96b0-0800200c9a66"
}

### deleting books
 DELETE http://localhost:4004/BooksSRV/Books/9a9349f1-efe4-11ee-96b0-0800200c9a66 HTTP/1.1


 