### reading data
GET   http://localhost:4004/BooksSRV/Books?$expand=address HTTP/1.1
### reading books

GET http://localhost:4004/BooksSRV/Books/9a9349f0-efe4-11ee-96b0-0800200c9a66 HTTP/1.1

### creating books
POST http://localhost:4004/BooksSRV/Books HTTP/1.1
Content-Type: application/json

 {
      "ID": "9a9349f3-efe4-11ee-96b0-0800200c9a66",
      "title": "C programming",
      "descr": "C language",
      "amount": 700,
      "email": "kalyan@gmail.com",
      "reldate": "2022-09-01",
      "phone": "9001706243",
      "author_ID": "9a9349f4-efe4-11ee-96b0-0800200c9a66"
    }
### reading data

GET http://localhost:4004/BooksSRV/Books?$expand=author,address HTTP/1.1

### reading address data

GET http://localhost:4004/BooksSRV/Address HTTP/1.1

### creating address data
POST  http://localhost:4004/BooksSRV/Address HTTP/1.1
Content-Type: application/json

{
"ID": "9a9349f3-efe5-11ee-96b0-0800200c9a66",
      "city": "Nellore",
      "address": "Bitragunta",
      "pincode": 51002,
      "street": "vaikuntapuram",
      "landmark": "water tank",
      "book_ID": "9a9349f4-efe4-11ee-96b0-0800200c9a66"
}
### reading authors

GET http://localhost:4004/BooksSRV/Authors HTTP/1.1

### creating author

POST http://localhost:4004/BooksSRV/Authors HTTP/1.1
Content-Type: application/json


{
    "ID": "9a9349f4-efe4-11ee-96b0-0800200c9a66",
      "name": "kalyani"
}

### creating books
POST http://localhost:4004/BooksSRV/Books HTTP/1.1
Content-Type: application/json


{
 "ID": "9a9349f1-efe4-11ee-96b0-0800200c9a66",
      "title": "SAP EWM",
      "descr": "EWM programming architecture",
      "amount": 900,
      "email": "ujwala@gmail.com",
      "phone": "9901706243",
      "author_ID": "9a9349f3-efe4-11ee-96b0-0800200c9a66"
}

### deleting books
 DELETE http://localhost:4004/BooksSRV/Books/9a9349f1-efe4-11ee-96b0-0800200c9a66 HTTP/1.1
